# Generated by Django 4.1 on 2022-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=35)),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
