# Generated by Django 4.1 on 2022-09-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_complete_todo_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
