# Generated by Django 4.1 on 2022-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_delete_user_remove_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notification',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='todo',
            name='plannedhours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='takenHours',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
